// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynbvwbfxbjlwhjuvczpe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InluYnZ3YmZ4Ympsd2hqdXZjenBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM3NjIxMzAsImV4cCI6MjA4OTMzODEzMH0.9x4KzvTTf7uqiJHgx_HOd1E3FAL-qnJTfSyghaQX0F4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});